In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [3]:
a=np.arange(1024)

In [11]:
samps=a.reshape(-1,8)
print(samps)

[[   0    1    2 ...    5    6    7]
 [   8    9   10 ...   13   14   15]
 [  16   17   18 ...   21   22   23]
 ...
 [1000 1001 1002 ... 1005 1006 1007]
 [1008 1009 1010 ... 1013 1014 1015]
 [1016 1017 1018 ... 1021 1022 1023]]


In [13]:
samps.transpose()[1]

array([   1,    9,   17,   25,   33,   41,   49,   57,   65,   73,   81,
         89,   97,  105,  113,  121,  129,  137,  145,  153,  161,  169,
        177,  185,  193,  201,  209,  217,  225,  233,  241,  249,  257,
        265,  273,  281,  289,  297,  305,  313,  321,  329,  337,  345,
        353,  361,  369,  377,  385,  393,  401,  409,  417,  425,  433,
        441,  449,  457,  465,  473,  481,  489,  497,  505,  513,  521,
        529,  537,  545,  553,  561,  569,  577,  585,  593,  601,  609,
        617,  625,  633,  641,  649,  657,  665,  673,  681,  689,  697,
        705,  713,  721,  729,  737,  745,  753,  761,  769,  777,  785,
        793,  801,  809,  817,  825,  833,  841,  849,  857,  865,  873,
        881,  889,  897,  905,  913,  921,  929,  937,  945,  953,  961,
        969,  977,  985,  993, 1001, 1009, 1017])